NOT_IN_GAMES_FULLNAME = ["Benin", "Burkina Faso", "Zambia", "Zimbabwe"]
NOT_IN_GAMES_ABBREV = ["ZIM"]

LOOKUP_FULLNAME = {
	"Algeria": "ALG",
	"Angola": "ANG",
	"Antigua": "ANT",
	"Argentina": "ARG",
	"Australia": "AUS",
	"Austria": "AUT",
	"Bahamas": "BAH",
	"Belarus": "BLR",
	"Belgium": "BEL",
	"Benin": "",
	"Bolivia": "BOL",
	"Bosnia and Herzegovina": "BIH",
	"Brazil": "BRA",
	"Bulgaria": "BUL",
	"Burkina Faso": "",
	"Burundi": "BDI",
	"CAF": "CAF",
	"Cameroon": "CMR",
	"Canada": "CAN",
	"Cape Verde": "CPV",
	"Chad": "CHA",
	"Chile": "CHI",
	"China": "CHN",
	"Chinese Taipei": "TPE",
	"Colombia": "COL",
	"Costa Rica": "CRC",
	"Cote d'Ivoire": "CIV",
	"Croatia": "CRO",
	"Cuba": "CUB",
	"Czech Republic": "CZE",
	"Dem.Rep. of Congo": "COD",
	"Dominican Republic": "DOM",
	"Ecuador": "ECU",
	"Egypt": "EGY",
	"Estonia": "EST",
	"Finland": "FIN",
	"France": "FRA",
	"Gabon": "GAB",
	"Georgia": "GEO",
	"Germany": "GER",
	"Great Britain": "GBR",
	"Greece": "GRE",
	"Guinea": "GUI",
	"Hong Kong": "HKG",
	"Hungary": "HUN",
	"Iceland": "ISL",
	"India": "IND",
	"Indonesia": "INA",
	"Iran": "IRI",
	"Iraq": "IRQ",
	"Israel": "ISR",
	"Italy": "ITA",
	"Japan": "JPN",
	"Jordan": "JOR",
	"Kazakhstan": "KAZ",
	"Kenya": "KEN",
	"Korea": "KOR",
	"Kosovo": "",
	"Latvia": "LAT",
	"Lebanon": "LBN",
	"Lithuania": "LTU",
	"Macau": "MAC",
	"Malaysia": "MAS",
	"Mali": "MLI",
	"Mexico": "MEX",
	"Montenegro": "MNE",
	"Morocco": "MAR",
	"Mozambique": "MOZ",
	"Myanmar": "MYA",
	"Netherlands": "NED",
	"New Zealand": "NZL",
	"Nicaragua": "NCA",
	"Nigeria": "NGR",
	"Palestine": "PLE",
	"Panama": "PAN",
	"Paraguay": "PAR",
	"Peru": "PER",
	"Philippines": "PHI",
	"Poland": "POL",
	"Puerto Rico": "PUR",
	"Qatar": "QAT",
	"Romania": "ROU",
	"Russia": "RUS",
	"Rwanda": "RWA",
	"Senegal": "SEN",
	"Serbia": "SRB",
	"Singapore": "SGP",
	"Slovenia": "SLO",
	"Somalia": "SOM",
	"South Africa": "RSA",
	"South Sudan": "SSD",
	"Spain": "ESP",
	"Sweden": "SWE",
	"Syria": "SYR",
	"Thailand": "THA",
	"Tunisia": "TUN",
	"Turkey": "TUR",
	"Uganda": "UGA",
	"Ukraine": "UKR",
	"Uruguay": "URU",
	"USA": "USA",
	"Venezuela": "VEN",
	"Vietnam": "VIE",
	"Virgin Islands": "ISV",
	"Zambia": "",
	"Zimbabwe": "ZIM"
}


LOOKUP_ABBREV = {
        "ALG": "Algeria",
        "ANG": "Angola",
	"ANT": "Antigua",
	"ARG": "Argentina",
	"AUS": "Australia",
	"AUT": "Austria",
	"BAH": "Bahamas",
	"BDI": "Burundi",
	"BEL": "Belgium",
	"BIH": "Bosnia and Herzegovina",
	"BLR": "Belarus",
	"BOL": "Bolivia",
	"BRA": "Brazil",
	"BUL": "Bulgaria",
	"CAF": "CAF",
	"CAN": "Canada",
	"CHA": "Chad",
	"CHI": "Chile",
	"CHN": "China",
	"CIV": "Cote d'Ivoire",
	"CMR": "Cameroon",
	"COD": "Dem.Rep. of Congo",
	"COL": "Colombia",
	"CPV": "Cape Verde",
	"CRC": "Costa Rica",
	"CRO": "Croatia",
	"CUB": "Cuba",
	"CZE": "Czech Republic",
	"DOM": "Dominican Republic",
	"ECU": "Ecuador",
	"EGY": "Egypt",
	"ESP": "Spain",
	"EST": "Estonia",
	"FIN": "Finland",
	"FRA": "France",
	"GAB": "Gabon",
	"GBR": "Great Britain",
	"GEO": "Georgia",
	"GER": "Germany",
	"GRE": "Greece",
	"GUI": "Guinea",
	"HKG": "Hong Kong",
	"HUN": "Hungary",
	"INA": "Indonesia",
	"IND": "India",
	"IRI": "Iran",
	"IRQ": "Iraq",
	"ISL": "Iceland",
	"ISR": "Israel",
	"ISV": "Virgin Islands",
	"ITA": "Italy",
	"JOR": "Jordan",
	"JPN": "Japan",
	"KAZ": "Kazakhstan",
	"KEN": "Kenya",
	"KOR": "Korea",
	"KOS": "Kosovo",
	"LAT": "Latvia",
	"LBN": "Lebanon",
	"LTU": "Lithuania",
	"MAC": "Macau",
	"MAR": "Morocco",
	"MAS": "Malaysia",
	"MEX": "Mexico",
	"MLI": "Mali",
	"MNE": "Montenegro",
	"MOZ": "Mozambique",
	"MYA": "Myanmar",
	"NCA": "Nicaragua",
	"NED": "Netherlands",
	"NGR": "Nigeria",
	"NZL": "New Zealand",
	"PAN": "Panama",
	"PAR": "Paraguay",
	"PER": "Peru",
	"PHI": "Philippines",
	"PLE": "Palestine",
	"POL": "Poland",
	"PUR": "Puerto Rico",
	"QAT": "Qatar",
	"ROU": "Romania",
	"RSA": "South Africa",
	"RUS": "Russia",
	"RWA": "Rwanda",
	"SEN": "Senegal",
	"SGP": "Singapore",
	"SLO": "Slovenia",
	"SOM": "Somalia",
	"SRB": "Serbia",
	"SSD": "South Sudan",
	"SWE": "Sweden",
	"SYR": "Syria",
	"THA": "Thailand",
	"TPE": "Chinese Taipei",
	"TUN": "Tunisia",
	"TUR": "Turkey",
	"UGA": "Uganda",
	"UKR": "Ukraine",
	"URU": "Uruguay",
	"USA": "USA",
	"VEN": "Venezuela",
	"VIE": "Vietnam",
	"ZIM": "Zimbabwe"
}

def to_abbrev(full_name):
    if full_name in LOOKUP_FULLNAME:
        return LOOKUP_FULLNAME[full_name]
    return ""

def from_abbrev(name):
    if name in LOOKUP_ABBREV:
        return LOOKUP_ABBREV[name]
    return ""
    
    
if __name__=='__main__':
    name = "AUS"
    full_name = from_abbrev(name)
    print(from_abbrev(name))
    print(to_abbrev(full_name))
